export const timezones = [
  { timezone: "Pacific/Midway", country: "United States" },
  { timezone: "Pacific/Honolulu", country: "United States" },
  { timezone: "America/Anchorage", country: "United States" },
  { timezone: "America/Los_Angeles", country: "United States" },
  { timezone: "America/Denver", country: "United States" },
  { timezone: "America/Chicago", country: "United States" },
  { timezone: "America/New_York", country: "United States" },
  { timezone: "America/Caracas", country: "Venezuela" },
  { timezone: "America/Sao_Paulo", country: "Brazil" },
  { timezone: "Atlantic/Azores", country: "Portugal" },
  { timezone: "Europe/London", country: "United Kingdom" },
  { timezone: "Europe/Berlin", country: "Germany" },
  { timezone: "Europe/Paris", country: "France" },
  { timezone: "Europe/Moscow", country: "Russia" },
  { timezone: "Asia/Dubai", country: "United Arab Emirates" },
  { timezone: "Asia/Karachi", country: "Pakistan" },
  { timezone: "Asia/Kolkata", country: "India" },
  { timezone: "Asia/Colombo", country: "Sri Lanka" },
  { timezone: "Asia/Bangkok", country: "Thailand" },
  { timezone: "Asia/Shanghai", country: "China" },
  { timezone: "Asia/Tokyo", country: "Japan" },
  { timezone: "Asia/Seoul", country: "South Korea" },
  { timezone: "Australia/Sydney", country: "Australia" },
  { timezone: "Pacific/Guam", country: "Guam" },
  { timezone: "Pacific/Fiji", country: "Fiji" },
  { timezone: "Pacific/Auckland", country: "New Zealand" },
  { timezone: "Africa/Cairo", country: "Egypt" },
  { timezone: "Africa/Johannesburg", country: "South Africa" },
  { timezone: "Africa/Lagos", country: "Nigeria" },
  { timezone: "Africa/Nairobi", country: "Kenya" },
  { timezone: "Europe/Madrid", country: "Spain" },
  { timezone: "Europe/Rome", country: "Italy" },
  { timezone: "Europe/Amsterdam", country: "Netherlands" },
  { timezone: "Europe/Zurich", country: "Switzerland" },
  { timezone: "Europe/Prague", country: "Czech Republic" },
  { timezone: "Europe/Vienna", country: "Austria" },
  { timezone: "Asia/Singapore", country: "Singapore" },
  { timezone: "Asia/Hong_Kong", country: "Hong Kong" },
  { timezone: "Asia/Kathmandu", country: "Nepal" },
  { timezone: "Asia/Yangon", country: "Myanmar" },
  { timezone: "Asia/Manila", country: "Philippines" },
  { timezone: "Asia/Kuala_Lumpur", country: "Malaysia" },
  { timezone: "Asia/Jakarta", country: "Indonesia" },
  { timezone: "Asia/Ho_Chi_Minh", country: "Vietnam" },
  { timezone: "Asia/Tashkent", country: "Uzbekistan" },
  { timezone: "Asia/Riyadh", country: "Saudi Arabia" },
  { timezone: "Asia/Tehran", country: "Iran" },
  { timezone: "Asia/Kabul", country: "Afghanistan" },
  { timezone: "Asia/Almaty", country: "Kazakhstan" },
  { timezone: "Asia/Dhaka", country: "Bangladesh" },
  { timezone: "Asia/Ulaanbaatar", country: "Mongolia" },
  { timezone: "Asia/Vladivostok", country: "Russia" },
  { timezone: "Australia/Adelaide", country: "Australia" },
  { timezone: "Australia/Perth", country: "Australia" },
  { timezone: "Pacific/Tahiti", country: "French Polynesia" },
  { timezone: "Pacific/Easter", country: "Chile" },
  { timezone: "Pacific/Noumea", country: "New Caledonia" },
  { timezone: "Pacific/Apia", country: "Samoa" },
  { timezone: "Pacific/Chatham", country: "New Zealand" },
  { timezone: "America/Mexico_City", country: "Mexico" },
  { timezone: "America/Bogota", country: "Colombia" },
  { timezone: "America/Lima", country: "Peru" },
  { timezone: "America/Montevideo", country: "Uruguay" },
  { timezone: "America/Asuncion", country: "Paraguay" },
  { timezone: "America/La_Paz", country: "Bolivia" },
  { timezone: "America/Santiago", country: "Chile" },
  { timezone: "America/Barbados", country: "Barbados" },
  { timezone: "America/Havana", country: "Cuba" },
  { timezone: "America/Kingston", country: "Jamaica" },
  { timezone: "America/Toronto", country: "Canada" },
  { timezone: "America/Vancouver", country: "Canada" },
  { timezone: "America/Buenos_Aires", country: "Argentina" },
  { timezone: "America/Guatemala", country: "Guatemala" },
  { timezone: "America/El_Salvador", country: "El Salvador" },
  { timezone: "America/Managua", country: "Nicaragua" },
  { timezone: "America/Costa_Rica", country: "Costa Rica" },
  { timezone: "America/Panama", country: "Panama" },
  { timezone: "Atlantic/Reykjavik", country: "Iceland" },
  { timezone: "Atlantic/Bermuda", country: "Bermuda" },
  { timezone: "Atlantic/Canary", country: "Spain" },
  { timezone: "Europe/Brussels", country: "Belgium" },
  { timezone: "Europe/Stockholm", country: "Sweden" },
  { timezone: "Europe/Oslo", country: "Norway" },
  { timezone: "Europe/Copenhagen", country: "Denmark" },
  { timezone: "Europe/Dublin", country: "Ireland" },
  { timezone: "Europe/Helsinki", country: "Finland" },
  { timezone: "Europe/Warsaw", country: "Poland" },
  { timezone: "Europe/Budapest", country: "Hungary" },
  { timezone: "Europe/Lisbon", country: "Portugal" },
  { timezone: "Europe/Athens", country: "Greece" },
  { timezone: "Europe/Sofia", country: "Bulgaria" },
  { timezone: "Europe/Istanbul", country: "Turkey" },
  { timezone: "Antarctica/Troll", country: "Norway" },
];
